### ISSUE TITLE
how to use on redux?

### ISSUE THREAD

**Issue by fallenmel** [Upstatement/react-router-guards#23]
how to use on redux?

redux provider and guardProvider

**Comment by joshpensky** [comment]
Hey @fallenmel, apologies for the delayed response!

We require that the `GuardProvider` component is inside a `Router` component and wraps any `GuardedRoute` components. Meanwhile, the `react-redux` package recommends wrapping your entire application in their `Provider` component. An example setup might look like:

```jsx
import React from 'react';
import { Provider } from 'react-redux';
import { BrowserRouter } from 'react-router-dom';
import { GuardProvider, GuardedRoute } from 'react-router-guards';
import store from './store';

const App = () => (
  <Provider store={store}>
    <BrowserRouter>
      <GuardProvider>
        <GuardedRoute path="/" component={Home} />
      </GuardProvider>
    </BrowserRouter>
  </Provider>
);

**Comment by joshpensky** [comment]
Going to close out this issue, but feel free to re-open if you have more questions!
