### ISSUE TITLE
Always rendering wildcard route

### ISSUE THREAD

**Issue by emachiels** [Upstatement/react-router-guards#29]
# Summary

Router wildcard is rendering both the requested route and wildcard route. Is it me, or is this a bug?
I didn't place this as a bug, since I am following the docs and it should be fine. It isn't though. 

## Relevant information

When trying to set up my routes using react-router-guards, I have some struggle to show a 404-page when no route was matched. 
According to the docs, the following structure should word:

```JSX
<GuardProvider loading={Loading} error={NotFound}>
    <GuardedRoute path="/login" exact component={Login} />
    <GuardProvider guards={[requireLogin]}>
        <GuardedRoute path="/" exact component={Home} />
        <GuardedRoute path="/about" exact component={About} />
    </GuardProvider>
    <GuardedRoute path="*" component={NotFound} />
</GuardProvider>
```

My structure looks like:

```JSX
<GuardProvider loading="loading..." error={FourOFourPage}>
    <GuardProvider guards={[guest]}>
        <GuardedRoute exact path="/" component={LoginPage} />
        <GuardedRoute exact path="/login" component={LoginPage} />
        <GuardedRoute exact path="/register" component={RegisterPage} />
    </GuardProvider>
    <GuardProvider guards={[auth]}>
        <GuardedRoute exact path="/me" component={MePage} />
    </GuardProvider>
    <GuardedRoute path="*" component={FourOFourPage} />
</GuardProvider>
```
And this renders both the valid route component AND the `FourOFourPage`-component. I tried using a Switch component from `react-router-dom`, but that doesn't work properly: it makes all routes outside the `GuardProvider` with the `guest` guard blank (instead of a preferred redirect)

The `guest` guard i checking if a session is active, and if true, redirect to /me.

The `auth` guard is checking if a session is active, and if false, redirect to /login. 

### Environment (if relevant)

Using:
`react-router-guards@1.0.1`
`react-router-dom@5.1.2`
`react-router@5.1.2`

Hopefully someone can help me! :)

**Comment by victorshaheen** [comment]
First

**Comment by joshpensky** [comment]
Hey! This looks to be an error on our part with some bad documentation

As of React Router v5, all of your route components should be wrapped in a `Switch`. This is what should allow React Router to correctly render only one route at a time. Unfortunately, this also means `GuardProvider` components can't be nested

As a way to get around this, you can use the `meta` prop on `GuardedRoute`s in order to conditionally apply guards to certain routes. 

In your given example, this could look something like

```jsx
const guest = (to, from, next) => {
  if (to.meta.guest) {
    // guest-only logic here
  } else {
    next();
};

const auth = (to, from, next) => {
  if (to.meta.auth) {
    // auth-only logic here
  } else {
    next();
};

// ...

<GuardProvider guards={[guest, auth]} loading="loading..." error={FourOFourPage}>
  <Switch>
    <GuardedRoute exact path="/" component={LoginPage} meta={{ guest: true }} />
    <GuardedRoute exact path="/login" component={LoginPage} meta={{ guest: true }} />
    <GuardedRoute exact path="/register" component={RegisterPage} meta={{ guest: true }} />
    <GuardedRoute exact path="/me" component={MePage} meta={{ auth: true }} />
    <GuardedRoute path="*" component={FourOFourPage} />
  </Switch>
</GuardProvider>
```

I hope this helps! We'll make sure to update that documentation as well

**Comment by emachiels** [comment]
Thanks for your reply @joshpensky! I like that structure less, but it will do. Any plans on adding some switch-logic yourself later on?
