### ISSUE TITLE
Redirect to requested page

### ISSUE THREAD

**Issue by georgejdli** [Upstatement/react-router-guards#49]
Is there a way to "record" what the requested protected route was?

Say for example:

```jsx
import React from 'react';
import { BrowserRouter } from 'react-router-dom';
import { GuardProvider, GuardedRoute } from 'react-router-guards';
import { About, Home, Loading, Login, NotFound } from 'pages';
import { getIsLoggedIn } from 'utils';

const requireLogin = (to, from, next) => {
  if (to.meta.auth) {
    if (getIsLoggedIn()) {
      next();
    }
    next.redirect('/login');
  } else {
    next();
  }
};

const App = () => (
  <BrowserRouter>
    <GuardProvider guards={[requireLogin]} loading={Loading} error={NotFound}>
      <Switch>
        <GuardedRoute path="/login" exact component={Login} />
        <GuardedRoute path="/" exact component={Home} meta={{ auth: true }} />
        <GuardedRoute path="/about" exact component={About} meta={{ auth: true }} />
        <GuardedRoute path="*" component={NotFound} />
      </Switch>
    </GuardProvider>
  </BrowserRouter>
);
```

Let's say user requests "/about" and gets redirected to "/login" because they are not logged in. After logging the user in is there a way to retrieve the path the user requested so that the application can then redirect them there (in this case "/about")?

**Comment by joshpensky** [comment]
Hey there! 👋 The `next.redirect()` function can accept a [string](https://reactrouter.com/web/api/Redirect/to-string) or [object](https://reactrouter.com/web/api/Redirect/to-object) location, similar to the `to` prop in React Router's [Redirect](https://reactrouter.com/web/api/Redirect) component.

Knowing this, we can pass an object to `next.redirect()` and use the `search` property to track the previously redirected path:

```js
const requireLogin = (to, from, next) => {
  if (to.meta.auth) {
    if (getIsLoggedIn()) {
      next();
    }
    next.redirect({
      pathname: '/login',
      search: `?redirectTo=${to.location.pathname}`
    });
  } else {
    next();
  }
};
```

We could also alternatively use route `state` to track the path:

```js
const requireLogin = (to, from, next) => {
  if (to.meta.auth) {
    if (getIsLoggedIn()) {
      next();
    }
    next.redirect({
      pathname: '/login',
      state: { redirectTo: to.location.pathname }
    });
  } else {
    next();
  }
};
```

Hope this helps!
