### ISSUE TITLE
How to access redux Store from inside the route guard

### ISSUE THREAD

**Issue by lalosh** [Upstatement/react-router-guards#50]
I need to access the store state and actions from inside the `guard` passed to the GuardProvider but I couldn't.

I've tried in multiple ways to access the store from inside the guard.

The final solution I had is making a HOC around GuardRoute that have access to the store using `connect` function

But the `projects` at the first render is being empty, and when we change the route at least one time the `projects` get updated.

Add to that, when I pass an action and get called inside the guard, the action is not dispatched!!

```ts
export const CustomRoute = connect(
    (state: any) => ({ state }),
    { openWarningDialog }
)
    (function _customRoute(props: RouteType) {

        return <GuardedRoute
            {...props}
            meta={{
                ...props?.meta,
                projects: props?.state?.getIn(['projects'])?.toJS(),
                openWarningDialog
            }} />
    });
```

**Comment by octopuss** [comment]
Maybe this will help you. I pass dispatch to the routes using meta and then call thunk action with "next()" passed as parameter. See in simplified example below

```
const AppContainer = () => {
	const dispatch = useDispatch();
	return (
		<GuardProvider guards={[dummyGuard]} error={NotFoundPage}>
                <GuardedRoute
			...
			meta={{ dispatch }}
                        guards={[routeGuard]}
			...
		/>
...
```

and the guard is 

```
const routeGuard = (to, from, next) => to.meta.dispatch(guardRouteAction(from, to, next))
 
const guardRouteAction = (to, from, next) => (dispatch, getState) => {
	const state = getState();
	if(!state.something) {
		Logger.info(`Guard disables rendering of  requested page`);
		dispatch(push('/notAlowed')))
	} else {
		Logger.info(`Guard allows rendering of  requested page`);
		next();
	}

}
```
this way you have state present in guard.

**Comment by joshpensky** [comment]
Since Redux is just a JS library at its core, you should be able to access the store's state and dispatch actions from inside the guard functions!

For example, you might have a `store` like so (taken from the [Redux Getting Started docs](https://redux.js.org/introduction/getting-started)):

```jsx
import { createStore } from 'redux';

function counterReducer(state = { value: 0 }, action) {
  switch (action.type) {
    case 'counter/incremented':
      return { value: state.value + 1 }
    case 'counter/decremented':
      return { value: state.value - 1 }
    default:
      return state
  }
}

export const store = createStore(counterReducer)
```

This is the same `store` that you passed to React Redux's `Provider` component at the top of your app (taken from the [React Redux Getting Started docs](https://react-redux.js.org/introduction/getting-started)):

```jsx
import { Provider } from 'react-redux';
import { store } from './store';

export function App() {
  return (
    <Provider store={store}>
      {/* ... */}
    </Provider>
  );
}
```

You can use the same `store` variable to access state and dispatch actions in guards:

```jsx
import { store } from './store';

const routeGuard = (to, from, next) => {
  // Access the store's state
  const value = store.getState();
  
  // Dispatch an action
  store.dispatch({ type: 'counter/incremented' });

  next();
}
```

I hope this helps!
